import { useQuery } from '@tanstack/react-query';

import {
  ClarifyingQuestionsResponseSchema,
  type ClarifyingQuestion,
} from '@shared/schemas/clarification';
import { EDGE_FUNCTIONS } from '@/constants/edge-functions';
import { useAuth } from '@/features/auth/useAuth';
import { callEdgeFunction } from '@/lib/edge';
import { logger } from '@/lib/logger';

export const clarifyingQuestionsQueryKey = (projectId: string) =>
  ['clarifying-questions', projectId] as const;

// Questions are generated by a query (not a mutation) so the result lives in the query cache rather
// than a single component-bound observer. That makes it survive StrictMode's dev remount and any
// later remount: the page renders from cache instead of from one observer that can be torn down
// mid-flight (which left the UI stuck on "Thinking…" even after a successful response).
export function useClarifyingQuestions(projectId: string) {
  const { session } = useAuth();
  const accessToken = session?.access_token;

  return useQuery<ClarifyingQuestion[], Error>({
    queryKey: clarifyingQuestionsQueryKey(projectId),
    queryFn: async () => {
      if (!accessToken) {
        throw new Error('NOT_AUTHENTICATED');
      }

      const data = await callEdgeFunction(
        EDGE_FUNCTIONS.GENERATE_CLARIFYING_QUESTIONS,
        { projectId },
        accessToken,
      );
      const parsed = ClarifyingQuestionsResponseSchema.safeParse(data);

      if (!parsed.success) {
        logger.error('clarification_invalid_shape', {
          issueCount: parsed.error.issues.length,
        });
        throw new Error('CLARIFICATION_INVALID_SHAPE');
      }

      return parsed.data.questions;
    },
    enabled: Boolean(accessToken) && projectId.length > 0,
    // Generation is an expensive one-shot AI call: never auto-retry or auto-refetch, and keep the
    // result for the session so revisiting the page does not regenerate (and re-bill) questions.
    // The page exposes a single manual retry via refetch().
    retry: false,
    staleTime: Infinity,
    gcTime: Infinity,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });
}
