export const EDGE_FUNCTIONS = {
  GENERATE_CLARIFYING_QUESTIONS: 'generate-clarifying-questions',
  GENERATE_PROJECT_BRIEF: 'generate-project-brief',
  GENERATE_PRD: 'generate-prd',
  REGENERATE_PRD_SECTION: 'regenerate-prd-section',
  SAVE_PRD_CONTENT: 'save-prd-content',
  GENERATE_ARCHITECTURE: 'generate-architecture',
  REGENERATE_ARCHITECTURE_SECTION: 'regenerate-architecture-section',
  SAVE_ARCHITECTURE_CONTENT: 'save-architecture-content',
  GENERATE_CONTEXT_FILES: 'generate-context-files',
  REGENERATE_CONTEXT_DOC: 'regenerate-context-doc',
  GENERATE_CHUNKS: 'generate-chunks',
  GENERATE_FEATURE_SPEC: 'generate-feature-spec',
  REGENERATE_FEATURE_SPEC_SECTION: 'regenerate-feature-spec-section',
  SAVE_FEATURE_SPEC_CONTENT: 'save-feature-spec-content',
  GENERATE_AGENT_PROMPT: 'generate-agent-prompt',
} as const;
